### ISSUE TITLE
USER STORY: Keep historical records.

### ISSUE THREAD

**Issue by KarMiles** [KarMiles/agile-practice#5]
As an **administrator** I can **keep record of all previous polls including voting details** so that I can **access historical records at any given time**.

# Acceptance criteria: 
- The system keeps records of all votes and all other historical input from users.
- Administrator can access records by date, poll, kind of input.

# Tasks:
* [ ] Choose database solution.
* [ ] Connect input with database.
* [ ] Create method to access database.
